### ISSUE TITLE
no depoupling on the opamps?

### ISSUE THREAD

**Issue by KeLaiFu** [m0xpd/encore#1]
excuse my noob question, but it seems you didn't include the usual decoupling caps on the opamps (not that I know what that means).

Is there a reason for that in this case or should I add them for 'good practice'?

**Comment by m0xpd** [comment]
Thanks for raising this interesting question - which I shall attempt to answer (despite being away from home on vacation, without access to the resources that would make answering easier - like my computer!)

Decoupling is - of course - important and necessary. You will see that I have added four 0.1uF capacitors to decouple the +/- 12V supply (these are, I think, C1, C2, C12 & C13). They are deliberately placed at either ‘end’ of the board.

I have not - however - placed individual decoupling capacitors for each of the four op-amp packages (and the LM13700), having found that the decoupling described above is adequate.

To that extent, I do not always the ‘good-practice’ of placing decoupling on each op-amp when there are multiple op-amps on a board; I suggest the benefits are questionable in certain practical applications.

Your ‘noob’ question needs no excusing; we were all ‘noobs’ once and some of us have the wisdom to be happy to remain ‘noobs’ all our lives! 

Thanks for your interest in encore!
